import { Knex } from 'knex';

const RolesTableName = 'roles';
const ScopedRolesTableName = 'scoped_roles';

// Frozen literal copies of ORGANIZATION_ROLE_TO_SCOPES_MAP / PROJECT_ROLE_TO_SCOPES_MAP
// (packages/common/src/authorization/orgRoleToScopeMapping.ts / roleToScopeMapping.ts)
// as of this migration's authoring -- per migrations/CLAUDE.md, migrations must not
// import from @lightdash/common, so this is a point-in-time snapshot, not a live link.
// Well-known role_uuid values are fixed here and mirrored in the application-level
// resolver (packages/common/src/authorization/systemRoleUuids.ts) so both sides agree
// on which UUID identifies which system role.
type SystemRoleSeed = {
    roleUuid: string;
    name: string;
    level: 'organization' | 'project';
    scopes: string[];
};

const ORGANIZATION_ROLE_SEEDS: SystemRoleSeed[] = [
    {
        roleUuid: 'caaf4f7b-e3dc-4ea7-bf9d-9be284c223f6',
        name: 'Member',
        level: 'organization',
        scopes: [
            'view:JobStatus@self',
            'view:PinnedItems',
            'view:OrganizationMemberProfile',
        ],
    },
    {
        roleUuid: '8e4cd2c9-c7f5-486e-8cac-d64866fa15c1',
        name: 'Viewer',
        level: 'organization',
        scopes: [
            'view:JobStatus@self',
            'view:PinnedItems',
            'view:OrganizationMemberProfile',
            'view:Dashboard',
            'view:SavedChart',
            'view:Space',
            'view:OrganizationDesign',
            'view:Project',
            'view:Organization',
            'manage:ExportCsv',
            'view:DashboardComments',
            'view:Tags',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
        ],
    },
    {
        roleUuid: 'e81a9b0c-6a08-44ad-baab-2f5a899cc3ed',
        name: 'Interactive Viewer',
        level: 'organization',
        scopes: [
            'view:JobStatus@self',
            'view:PinnedItems',
            'view:OrganizationMemberProfile',
            'view:Dashboard',
            'view:SavedChart',
            'view:Space',
            'view:OrganizationDesign',
            'view:Project',
            'view:Organization',
            'manage:ExportCsv',
            'view:DashboardComments',
            'view:Tags',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
            'create:Job',
            'view:Job@self',
            'view:UnderlyingData',
            'view:SemanticViewer',
            'manage:ChangeCsvResults',
            'manage:Explore',
            'create:ScheduledDeliveries',
            'manage:ScheduledDeliveries@self',
            'manage:GoogleSheets',
            'create:DashboardComments',
            'manage:Dashboard@space',
            'manage:SavedChart@space',
            'manage:SemanticViewer@space',
            'manage:DataApp@space',
            'manage:Space@assigned',
            'view:AiAgent',
            'view:OrganizationAiAgent',
            'view:AiAgentDocument',
            'create:AiAgentThread',
            'view:ContentVerification',
            'view:DataApp',
            'view:DataApp@self',
            'manage:DataApp@self',
            'view:ExternalConnection',
        ],
    },
    {
        roleUuid: 'cde89f4f-f971-4f7b-9d18-5b6082eb5ae0',
        name: 'Editor',
        level: 'organization',
        scopes: [
            'view:JobStatus@self',
            'view:PinnedItems',
            'view:OrganizationMemberProfile',
            'view:Dashboard',
            'view:SavedChart',
            'view:Space',
            'view:OrganizationDesign',
            'view:Project',
            'view:Organization',
            'manage:ExportCsv',
            'view:DashboardComments',
            'view:Tags',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
            'create:Job',
            'view:Job@self',
            'view:UnderlyingData',
            'view:SemanticViewer',
            'manage:ChangeCsvResults',
            'manage:Explore',
            'create:ScheduledDeliveries',
            'manage:ScheduledDeliveries@self',
            'manage:GoogleSheets',
            'create:DashboardComments',
            'manage:Dashboard@space',
            'manage:SavedChart@space',
            'manage:SemanticViewer@space',
            'manage:DataApp@space',
            'manage:Space@assigned',
            'view:AiAgent',
            'view:OrganizationAiAgent',
            'view:AiAgentDocument',
            'create:AiAgentThread',
            'view:ContentVerification',
            'view:DataApp',
            'view:DataApp@self',
            'manage:DataApp@self',
            'view:ExternalConnection',
            'create:DataApp',
            'manage:Space@public',
            'create:Space',
            'manage:Job',
            'manage:PinnedItems',
            'manage:DashboardComments',
            'manage:SemanticViewer',
            'manage:Tags',
            'manage:MetricsTree',
            'view:OrganizationWarehouseCredentials',
            'view:ContentAsCode',
            'create:ContentAsCode',
        ],
    },
    {
        roleUuid: '76ce1b01-74e2-475a-b05d-7fa8ba4590c1',
        name: 'Developer',
        level: 'organization',
        scopes: [
            'view:JobStatus@self',
            'view:PinnedItems',
            'view:OrganizationMemberProfile',
            'view:Dashboard',
            'view:SavedChart',
            'view:Space',
            'view:OrganizationDesign',
            'view:Project',
            'view:Organization',
            'manage:ExportCsv',
            'view:DashboardComments',
            'view:Tags',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
            'create:Job',
            'view:Job@self',
            'view:UnderlyingData',
            'view:SemanticViewer',
            'manage:ChangeCsvResults',
            'manage:Explore',
            'create:ScheduledDeliveries',
            'manage:ScheduledDeliveries@self',
            'manage:GoogleSheets',
            'create:DashboardComments',
            'manage:Dashboard@space',
            'manage:SavedChart@space',
            'manage:SemanticViewer@space',
            'manage:DataApp@space',
            'manage:Space@assigned',
            'view:AiAgent',
            'view:OrganizationAiAgent',
            'view:AiAgentDocument',
            'create:AiAgentThread',
            'view:ContentVerification',
            'view:DataApp',
            'view:DataApp@self',
            'manage:DataApp@self',
            'view:ExternalConnection',
            'create:DataApp',
            'manage:Space@public',
            'create:Space',
            'manage:Job',
            'manage:PinnedItems',
            'manage:DashboardComments',
            'manage:SemanticViewer',
            'manage:Tags',
            'manage:MetricsTree',
            'view:OrganizationWarehouseCredentials',
            'view:ContentAsCode',
            'create:ContentAsCode',
            'manage:PreAggregation',
            'manage:VirtualView',
            'manage:CustomSql',
            'manage:CustomFields',
            'view:CompiledSql',
            'manage:CustomSqlTableCalculations',
            'manage:SqlRunner',
            'manage:Validation',
            'view:SourceCode',
            'manage:SourceCode',
            'promote:SavedChart@space',
            'promote:Dashboard@space',
            'manage:CompileProject',
            'create:Project@preview',
            'update:Project',
            'manage:DeployProject@self',
            'delete:Project@self',
            'manage:SpotlightTableConfig',
            'manage:ContentAsCode',
            'manage:ContentAsCode@self',
            'view:JobStatus',
            'manage:AiAgent',
            'manage:OrganizationAiAgent',
            'manage:AiAgentDocument',
            'manage:AiAgentThread@self',
            'manage:ContentVerification',
            'create:AiDeepResearch',
        ],
    },
    {
        roleUuid: '0afcdc72-2c59-4873-949e-92bbd5a78e97',
        name: 'Admin',
        level: 'organization',
        scopes: [
            'view:JobStatus@self',
            'view:PinnedItems',
            'view:OrganizationMemberProfile',
            'view:Dashboard',
            'view:SavedChart',
            'view:Space',
            'view:OrganizationDesign',
            'view:Project',
            'view:Organization',
            'manage:ExportCsv',
            'view:DashboardComments',
            'view:Tags',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
            'create:Job',
            'view:Job@self',
            'view:UnderlyingData',
            'view:SemanticViewer',
            'manage:ChangeCsvResults',
            'manage:Explore',
            'create:ScheduledDeliveries',
            'manage:ScheduledDeliveries@self',
            'manage:GoogleSheets',
            'create:DashboardComments',
            'manage:Dashboard@space',
            'manage:SavedChart@space',
            'manage:SemanticViewer@space',
            'manage:DataApp@space',
            'manage:Space@assigned',
            'view:AiAgent',
            'view:OrganizationAiAgent',
            'view:AiAgentDocument',
            'create:AiAgentThread',
            'view:ContentVerification',
            'view:DataApp',
            'view:DataApp@self',
            'manage:DataApp@self',
            'view:ExternalConnection',
            'create:DataApp',
            'manage:Space@public',
            'create:Space',
            'manage:Job',
            'manage:PinnedItems',
            'manage:DashboardComments',
            'manage:SemanticViewer',
            'manage:Tags',
            'manage:MetricsTree',
            'view:OrganizationWarehouseCredentials',
            'view:ContentAsCode',
            'create:ContentAsCode',
            'manage:PreAggregation',
            'manage:VirtualView',
            'manage:CustomSql',
            'manage:CustomFields',
            'view:CompiledSql',
            'manage:CustomSqlTableCalculations',
            'manage:SqlRunner',
            'manage:Validation',
            'view:SourceCode',
            'manage:SourceCode',
            'promote:SavedChart@space',
            'promote:Dashboard@space',
            'manage:CompileProject',
            'create:Project@preview',
            'update:Project',
            'manage:DeployProject@self',
            'delete:Project@self',
            'manage:SpotlightTableConfig',
            'manage:ContentAsCode',
            'manage:ContentAsCode@self',
            'view:JobStatus',
            'manage:AiAgent',
            'manage:OrganizationAiAgent',
            'manage:AiAgentDocument',
            'manage:AiAgentThread@self',
            'manage:ContentVerification',
            'create:AiDeepResearch',
            'view:Roadmap',
            'manage:DataApp',
            'manage:DataAppDependency',
            'manage:ExternalConnection',
            'manage:OrganizationDesign',
            'manage:Dashboard',
            'manage:Space',
            'manage:SavedChart',
            'delete:Project',
            'manage:Project',
            'manage:InviteLink',
            'manage:Organization',
            'manage:OrganizationColorPalette',
            'view:Analytics',
            'manage:OrganizationMemberProfile',
            'manage:ProjectHomepage',
            'manage:Group',
            'manage:OrganizationWarehouseCredentials',
            'view:AiAgentThread',
            'manage:AiAgentThread',
            'manage:ScheduledDeliveries',
            'manage:DeletedContent',
            'manage:GitIntegration',
            'manage:DeployProject',
            'impersonate:User',
        ],
    },
];

const PROJECT_ROLE_SEEDS: SystemRoleSeed[] = [
    {
        roleUuid: '1cfe77eb-6715-4d8c-8e9f-92af4960b5c4',
        name: 'Viewer',
        level: 'project',
        scopes: [
            'view:Dashboard',
            'view:JobStatus@self',
            'view:SavedChart',
            'view:Space',
            'view:Project',
            'view:PinnedItems',
            'view:DashboardComments',
            'view:Tags',
            'manage:ExportCsv',
            'view:Organization',
            'view:OrganizationMemberProfile',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
            'view:OrganizationDesign',
        ],
    },
    {
        roleUuid: 'a6dd3176-8f48-442c-90dd-066d3d624fcf',
        name: 'Interactive Viewer',
        level: 'project',
        scopes: [
            'view:Dashboard',
            'view:JobStatus@self',
            'view:SavedChart',
            'view:Space',
            'view:Project',
            'view:PinnedItems',
            'view:DashboardComments',
            'view:Tags',
            'manage:ExportCsv',
            'view:Organization',
            'view:OrganizationMemberProfile',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
            'view:OrganizationDesign',
            'view:UnderlyingData',
            'view:SemanticViewer',
            'manage:Explore',
            'manage:ChangeCsvResults',
            'create:ScheduledDeliveries',
            'manage:ScheduledDeliveries@self',
            'create:DashboardComments',
            'manage:GoogleSheets',
            'create:Job',
            'view:Job',
            'view:Job@self',
            'manage:Dashboard@space',
            'manage:SavedChart@space',
            'manage:SemanticViewer@space',
            'manage:DataApp@space',
            'manage:Space@assigned',
            'view:AiAgent',
            'view:OrganizationAiAgent',
            'view:AiAgentDocument',
            'create:AiAgentThread',
            'view:DataApp',
            'view:DataApp@self',
            'manage:DataApp@self',
            'view:ExternalConnection',
            'view:ContentVerification',
        ],
    },
    {
        roleUuid: '1ba5dc14-43c0-4f23-a7ff-4e25543cdb06',
        name: 'Editor',
        level: 'project',
        scopes: [
            'view:Dashboard',
            'view:JobStatus@self',
            'view:SavedChart',
            'view:Space',
            'view:Project',
            'view:PinnedItems',
            'view:DashboardComments',
            'view:Tags',
            'manage:ExportCsv',
            'view:Organization',
            'view:OrganizationMemberProfile',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
            'view:OrganizationDesign',
            'view:UnderlyingData',
            'view:SemanticViewer',
            'manage:Explore',
            'manage:ChangeCsvResults',
            'create:ScheduledDeliveries',
            'manage:ScheduledDeliveries@self',
            'create:DashboardComments',
            'manage:GoogleSheets',
            'create:Job',
            'view:Job',
            'view:Job@self',
            'manage:Dashboard@space',
            'manage:SavedChart@space',
            'manage:SemanticViewer@space',
            'manage:DataApp@space',
            'manage:Space@assigned',
            'view:AiAgent',
            'view:OrganizationAiAgent',
            'view:AiAgentDocument',
            'create:AiAgentThread',
            'view:DataApp',
            'view:DataApp@self',
            'manage:DataApp@self',
            'view:ExternalConnection',
            'view:ContentVerification',
            'create:Space',
            'manage:Space@public',
            'manage:Job',
            'manage:PinnedItems',
            'manage:DashboardComments',
            'manage:Tags',
            'manage:SemanticViewer',
            'view:OrganizationWarehouseCredentials',
            'manage:MetricsTree',
            'manage:AiAgentThread@self',
            'view:ContentAsCode',
            'create:ContentAsCode',
            'create:DataApp',
        ],
    },
    {
        roleUuid: '324a01ee-a679-4559-90a4-99c70ef467eb',
        name: 'Developer',
        level: 'project',
        scopes: [
            'view:Dashboard',
            'view:JobStatus@self',
            'view:SavedChart',
            'view:Space',
            'view:Project',
            'view:PinnedItems',
            'view:DashboardComments',
            'view:Tags',
            'manage:ExportCsv',
            'view:Organization',
            'view:OrganizationMemberProfile',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
            'view:OrganizationDesign',
            'view:UnderlyingData',
            'view:SemanticViewer',
            'manage:Explore',
            'manage:ChangeCsvResults',
            'create:ScheduledDeliveries',
            'manage:ScheduledDeliveries@self',
            'create:DashboardComments',
            'manage:GoogleSheets',
            'create:Job',
            'view:Job',
            'view:Job@self',
            'manage:Dashboard@space',
            'manage:SavedChart@space',
            'manage:SemanticViewer@space',
            'manage:DataApp@space',
            'manage:Space@assigned',
            'view:AiAgent',
            'view:OrganizationAiAgent',
            'view:AiAgentDocument',
            'create:AiAgentThread',
            'view:DataApp',
            'view:DataApp@self',
            'manage:DataApp@self',
            'view:ExternalConnection',
            'view:ContentVerification',
            'create:Space',
            'manage:Space@public',
            'manage:Job',
            'manage:PinnedItems',
            'manage:DashboardComments',
            'manage:Tags',
            'manage:SemanticViewer',
            'view:OrganizationWarehouseCredentials',
            'manage:MetricsTree',
            'manage:AiAgentThread@self',
            'view:ContentAsCode',
            'create:ContentAsCode',
            'create:DataApp',
            'manage:PreAggregation',
            'manage:VirtualView',
            'create:VirtualView',
            'delete:VirtualView',
            'manage:CustomSql',
            'manage:CustomFields',
            'view:CompiledSql',
            'manage:CustomSqlTableCalculations',
            'manage:SqlRunner',
            'manage:Validation',
            'manage:CompileProject',
            'manage:DeployProject',
            'manage:DeployProject@self',
            'create:Project@preview',
            'delete:Project@self',
            'update:Project',
            'update:Project@self',
            'manage:Dashboard@self',
            'manage:SavedChart@self',
            'manage:Space@self',
            'manage:Explore@self',
            'view:JobStatus',
            'view:SourceCode',
            'manage:SourceCode',
            'promote:Dashboard',
            'promote:Dashboard@space',
            'promote:SavedChart',
            'promote:SavedChart@space',
            'manage:SpotlightTableConfig',
            'manage:ContentAsCode',
            'manage:ContentAsCode@self',
            'manage:AiAgent',
            'manage:OrganizationAiAgent',
            'manage:AiAgentDocument',
            'manage:ContentVerification',
            'create:AiDeepResearch',
        ],
    },
    {
        roleUuid: '63718c68-6e0b-404c-9e92-101513beb7fb',
        name: 'Admin',
        level: 'project',
        scopes: [
            'view:Dashboard',
            'view:JobStatus@self',
            'view:SavedChart',
            'view:Space',
            'view:Project',
            'view:PinnedItems',
            'view:DashboardComments',
            'view:Tags',
            'manage:ExportCsv',
            'view:Organization',
            'view:OrganizationMemberProfile',
            'view:MetricsTree',
            'view:SpotlightTableConfig',
            'view:AiAgentThread@self',
            'view:OrganizationDesign',
            'view:UnderlyingData',
            'view:SemanticViewer',
            'manage:Explore',
            'manage:ChangeCsvResults',
            'create:ScheduledDeliveries',
            'manage:ScheduledDeliveries@self',
            'create:DashboardComments',
            'manage:GoogleSheets',
            'create:Job',
            'view:Job',
            'view:Job@self',
            'manage:Dashboard@space',
            'manage:SavedChart@space',
            'manage:SemanticViewer@space',
            'manage:DataApp@space',
            'manage:Space@assigned',
            'view:AiAgent',
            'view:OrganizationAiAgent',
            'view:AiAgentDocument',
            'create:AiAgentThread',
            'view:DataApp',
            'view:DataApp@self',
            'manage:DataApp@self',
            'view:ExternalConnection',
            'view:ContentVerification',
            'create:Space',
            'manage:Space@public',
            'manage:Job',
            'manage:PinnedItems',
            'manage:DashboardComments',
            'manage:Tags',
            'manage:SemanticViewer',
            'view:OrganizationWarehouseCredentials',
            'manage:MetricsTree',
            'manage:AiAgentThread@self',
            'view:ContentAsCode',
            'create:ContentAsCode',
            'create:DataApp',
            'manage:PreAggregation',
            'manage:VirtualView',
            'create:VirtualView',
            'delete:VirtualView',
            'manage:CustomSql',
            'manage:CustomFields',
            'view:CompiledSql',
            'manage:CustomSqlTableCalculations',
            'manage:SqlRunner',
            'manage:Validation',
            'manage:CompileProject',
            'manage:DeployProject',
            'manage:DeployProject@self',
            'create:Project@preview',
            'delete:Project@self',
            'update:Project',
            'update:Project@self',
            'manage:Dashboard@self',
            'manage:SavedChart@self',
            'manage:Space@self',
            'manage:Explore@self',
            'view:JobStatus',
            'view:SourceCode',
            'manage:SourceCode',
            'promote:Dashboard',
            'promote:Dashboard@space',
            'promote:SavedChart',
            'promote:SavedChart@space',
            'manage:SpotlightTableConfig',
            'manage:ContentAsCode',
            'manage:ContentAsCode@self',
            'manage:AiAgent',
            'manage:OrganizationAiAgent',
            'manage:AiAgentDocument',
            'manage:ContentVerification',
            'create:AiDeepResearch',
            'manage:DataApp',
            'manage:DataAppDependency',
            'manage:ExternalConnection',
            'manage:OrganizationDesign',
            'delete:Project',
            'view:Analytics',
            'manage:Dashboard',
            'manage:Space',
            'manage:Project',
            'manage:SavedChart',
            'manage:DeletedContent',
            'manage:ProjectHomepage',
            'view:AiAgentThread',
            'manage:AiAgentThread',
            'manage:ScheduledDeliveries',
            'manage:OrganizationMemberProfile',
            'manage:Group',
            'manage:InviteLink',
            'manage:GitIntegration',
            'manage:OrganizationWarehouseCredentials',
            'manage:Organization',
            'manage:OrganizationColorPalette',
            'view:Roadmap',
            'impersonate:User',
            'manage:PersonalAccessToken',
        ],
    },
];

const ALL_SEEDS = [...ORGANIZATION_ROLE_SEEDS, ...PROJECT_ROLE_SEEDS];

export async function up(knex: Knex): Promise<void> {
    await knex.transaction(async (trx) => {
        // Cast: the shared DbRoleInsert/DbScopedRoleInsert app types (picked
        // up automatically via knex's table-name type augmentation) require
        // non-null organization_uuid/created_by/granted_by, since every
        // caller until now only ever inserted user-owned roles. System roles
        // are a legitimately different, DB-schema-valid case (the
        // user_roles_need_org CHECK constraint requires organization_uuid IS
        // NULL for owner_type='system') -- widening those app types is out
        // of scope for this migration; it belongs with the follow-up work
        // that makes application code actually read these rows.
        await trx(RolesTableName).insert(
            ALL_SEEDS.map((seed) => ({
                role_uuid: seed.roleUuid,
                name: seed.name,
                description: null,
                organization_uuid: null,
                created_by: null,
                owner_type: 'system',
                level: seed.level,
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
            })) as any[],
        );

        await trx(ScopedRolesTableName).insert(
            ALL_SEEDS.flatMap(
                (seed) =>
                    seed.scopes.map((scopeName) => ({
                        role_uuid: seed.roleUuid,
                        scope_name: scopeName,
                        granted_by: null,
                    })),
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
            ) as any[],
        );
    });
}

export async function down(knex: Knex): Promise<void> {
    const roleUuids = ALL_SEEDS.map((seed) => seed.roleUuid);
    await knex.transaction(async (trx) => {
        await trx(ScopedRolesTableName)
            .whereIn('role_uuid', roleUuids)
            .delete();
        await trx(RolesTableName).whereIn('role_uuid', roleUuids).delete();
    });
}
