import { readFileSync } from 'fs';
import { join } from 'path';
import { ProjectMemberRole } from '../types/projectMemberRole';
import { PROJECT_ROLE_TO_SCOPES_MAP } from './roleToScopeMapping';

/**
 * Given: `PROJECT_ROLE_TO_SCOPES_MAP` was computed at module-load time by
 *   looping over `ROLE_HIERARCHY` and unioning `BASE_ROLE_SCOPES` cumulatively
 *   -- itself a form of inheritance-by-composition-in-a-loop, not the flat,
 *   explicit data the scope-composed model calls for.
 * When: the implementation is flattened into literal per-role arrays.
 * Then: (a) the exact same set of scopes is produced for every role (this
 *   fixture is the golden master, captured from the pre-flattening output),
 *   and (b) no runtime union/loop composition remains in the source.
 */

// Captured verbatim from PROJECT_ROLE_TO_SCOPES_MAP's output before
// flattening (packages/common/src/authorization/_diag.test.ts, deleted after
// use). This is the behavior-preservation contract for the flattening --
// order doesn't matter functionally (scopes are applied via
// `context.scopes.forEach`, order-independent), so comparisons below are
// set-based.
const GOLDEN_MASTER: Record<ProjectMemberRole, string[]> = {
    [ProjectMemberRole.VIEWER]: [
        'view:Dashboard',
        'view:JobStatus@self',
        'view:SavedChart',
        'view:Space',
        'view:Project',
        'view:PinnedItems',
        'view:DashboardComments',
        'view:Tags',
        'manage:ExportCsv',
        'view:Organization',
        'view:OrganizationMemberProfile',
        'view:MetricsTree',
        'view:SpotlightTableConfig',
        'view:AiAgentThread@self',
        'view:OrganizationDesign',
    ],
    [ProjectMemberRole.INTERACTIVE_VIEWER]: [
        'view:Dashboard',
        'view:JobStatus@self',
        'view:SavedChart',
        'view:Space',
        'view:Project',
        'view:PinnedItems',
        'view:DashboardComments',
        'view:Tags',
        'manage:ExportCsv',
        'view:Organization',
        'view:OrganizationMemberProfile',
        'view:MetricsTree',
        'view:SpotlightTableConfig',
        'view:AiAgentThread@self',
        'view:OrganizationDesign',
        'view:UnderlyingData',
        'view:SemanticViewer',
        'manage:Explore',
        'manage:ChangeCsvResults',
        'create:ScheduledDeliveries',
        'manage:ScheduledDeliveries@self',
        'create:DashboardComments',
        'manage:GoogleSheets',
        'create:Job',
        'view:Job',
        'view:Job@self',
        'manage:Dashboard@space',
        'manage:SavedChart@space',
        'manage:SemanticViewer@space',
        'manage:DataApp@space',
        'manage:Space@assigned',
        'view:AiAgent',
        'view:OrganizationAiAgent',
        'view:AiAgentDocument',
        'create:AiAgentThread',
        'view:DataApp',
        'view:DataApp@self',
        'manage:DataApp@self',
        'view:ExternalConnection',
        'view:ContentVerification',
    ],
    [ProjectMemberRole.EDITOR]: [
        'view:Dashboard',
        'view:JobStatus@self',
        'view:SavedChart',
        'view:Space',
        'view:Project',
        'view:PinnedItems',
        'view:DashboardComments',
        'view:Tags',
        'manage:ExportCsv',
        'view:Organization',
        'view:OrganizationMemberProfile',
        'view:MetricsTree',
        'view:SpotlightTableConfig',
        'view:AiAgentThread@self',
        'view:OrganizationDesign',
        'view:UnderlyingData',
        'view:SemanticViewer',
        'manage:Explore',
        'manage:ChangeCsvResults',
        'create:ScheduledDeliveries',
        'manage:ScheduledDeliveries@self',
        'create:DashboardComments',
        'manage:GoogleSheets',
        'create:Job',
        'view:Job',
        'view:Job@self',
        'manage:Dashboard@space',
        'manage:SavedChart@space',
        'manage:SemanticViewer@space',
        'manage:DataApp@space',
        'manage:Space@assigned',
        'view:AiAgent',
        'view:OrganizationAiAgent',
        'view:AiAgentDocument',
        'create:AiAgentThread',
        'view:DataApp',
        'view:DataApp@self',
        'manage:DataApp@self',
        'view:ExternalConnection',
        'view:ContentVerification',
        'create:Space',
        'manage:Space@public',
        'manage:Job',
        'manage:PinnedItems',
        'manage:DashboardComments',
        'manage:Tags',
        'manage:SemanticViewer',
        'view:OrganizationWarehouseCredentials',
        'manage:MetricsTree',
        'manage:AiAgentThread@self',
        'view:ContentAsCode',
        'create:ContentAsCode',
        'create:DataApp',
    ],
    [ProjectMemberRole.DEVELOPER]: [
        'view:Dashboard',
        'view:JobStatus@self',
        'view:SavedChart',
        'view:Space',
        'view:Project',
        'view:PinnedItems',
        'view:DashboardComments',
        'view:Tags',
        'manage:ExportCsv',
        'view:Organization',
        'view:OrganizationMemberProfile',
        'view:MetricsTree',
        'view:SpotlightTableConfig',
        'view:AiAgentThread@self',
        'view:OrganizationDesign',
        'view:UnderlyingData',
        'view:SemanticViewer',
        'manage:Explore',
        'manage:ChangeCsvResults',
        'create:ScheduledDeliveries',
        'manage:ScheduledDeliveries@self',
        'create:DashboardComments',
        'manage:GoogleSheets',
        'create:Job',
        'view:Job',
        'view:Job@self',
        'manage:Dashboard@space',
        'manage:SavedChart@space',
        'manage:SemanticViewer@space',
        'manage:DataApp@space',
        'manage:Space@assigned',
        'view:AiAgent',
        'view:OrganizationAiAgent',
        'view:AiAgentDocument',
        'create:AiAgentThread',
        'view:DataApp',
        'view:DataApp@self',
        'manage:DataApp@self',
        'view:ExternalConnection',
        'view:ContentVerification',
        'create:Space',
        'manage:Space@public',
        'manage:Job',
        'manage:PinnedItems',
        'manage:DashboardComments',
        'manage:Tags',
        'manage:SemanticViewer',
        'view:OrganizationWarehouseCredentials',
        'manage:MetricsTree',
        'manage:AiAgentThread@self',
        'view:ContentAsCode',
        'create:ContentAsCode',
        'create:DataApp',
        'manage:PreAggregation',
        'manage:VirtualView',
        'create:VirtualView',
        'delete:VirtualView',
        'manage:CustomSql',
        'manage:CustomFields',
        'view:CompiledSql',
        'manage:CustomSqlTableCalculations',
        'manage:SqlRunner',
        'manage:Validation',
        'manage:CompileProject',
        'manage:DeployProject',
        'manage:DeployProject@self',
        'create:Project@preview',
        'delete:Project@self',
        'update:Project',
        'update:Project@self',
        'manage:Dashboard@self',
        'manage:SavedChart@self',
        'manage:Space@self',
        'manage:Explore@self',
        'view:JobStatus',
        'view:SourceCode',
        'manage:SourceCode',
        'promote:Dashboard',
        'promote:Dashboard@space',
        'promote:SavedChart',
        'promote:SavedChart@space',
        'manage:SpotlightTableConfig',
        'manage:ContentAsCode',
        'manage:ContentAsCode@self',
        'manage:AiAgent',
        'manage:OrganizationAiAgent',
        'manage:AiAgentDocument',
        'manage:ContentVerification',
        'create:AiDeepResearch',
    ],
    [ProjectMemberRole.ADMIN]: [
        'view:Dashboard',
        'view:JobStatus@self',
        'view:SavedChart',
        'view:Space',
        'view:Project',
        'view:PinnedItems',
        'view:DashboardComments',
        'view:Tags',
        'manage:ExportCsv',
        'view:Organization',
        'view:OrganizationMemberProfile',
        'view:MetricsTree',
        'view:SpotlightTableConfig',
        'view:AiAgentThread@self',
        'view:OrganizationDesign',
        'view:UnderlyingData',
        'view:SemanticViewer',
        'manage:Explore',
        'manage:ChangeCsvResults',
        'create:ScheduledDeliveries',
        'manage:ScheduledDeliveries@self',
        'create:DashboardComments',
        'manage:GoogleSheets',
        'create:Job',
        'view:Job',
        'view:Job@self',
        'manage:Dashboard@space',
        'manage:SavedChart@space',
        'manage:SemanticViewer@space',
        'manage:DataApp@space',
        'manage:Space@assigned',
        'view:AiAgent',
        'view:OrganizationAiAgent',
        'view:AiAgentDocument',
        'create:AiAgentThread',
        'view:DataApp',
        'view:DataApp@self',
        'manage:DataApp@self',
        'view:ExternalConnection',
        'view:ContentVerification',
        'create:Space',
        'manage:Space@public',
        'manage:Job',
        'manage:PinnedItems',
        'manage:DashboardComments',
        'manage:Tags',
        'manage:SemanticViewer',
        'view:OrganizationWarehouseCredentials',
        'manage:MetricsTree',
        'manage:AiAgentThread@self',
        'view:ContentAsCode',
        'create:ContentAsCode',
        'create:DataApp',
        'manage:PreAggregation',
        'manage:VirtualView',
        'create:VirtualView',
        'delete:VirtualView',
        'manage:CustomSql',
        'manage:CustomFields',
        'view:CompiledSql',
        'manage:CustomSqlTableCalculations',
        'manage:SqlRunner',
        'manage:Validation',
        'manage:CompileProject',
        'manage:DeployProject',
        'manage:DeployProject@self',
        'create:Project@preview',
        'delete:Project@self',
        'update:Project',
        'update:Project@self',
        'manage:Dashboard@self',
        'manage:SavedChart@self',
        'manage:Space@self',
        'manage:Explore@self',
        'view:JobStatus',
        'view:SourceCode',
        'manage:SourceCode',
        'promote:Dashboard',
        'promote:Dashboard@space',
        'promote:SavedChart',
        'promote:SavedChart@space',
        'manage:SpotlightTableConfig',
        'manage:ContentAsCode',
        'manage:ContentAsCode@self',
        'manage:AiAgent',
        'manage:OrganizationAiAgent',
        'manage:AiAgentDocument',
        'manage:ContentVerification',
        'create:AiDeepResearch',
        'manage:DataApp',
        'manage:DataAppDependency',
        'manage:ExternalConnection',
        'manage:OrganizationDesign',
        'delete:Project',
        'view:Analytics',
        'manage:Dashboard',
        'manage:Space',
        'manage:Project',
        'manage:SavedChart',
        'manage:DeletedContent',
        'manage:ProjectHomepage',
        'view:AiAgentThread',
        'manage:AiAgentThread',
        'manage:ScheduledDeliveries',
        'manage:OrganizationMemberProfile',
        'manage:Group',
        'manage:InviteLink',
        'manage:GitIntegration',
        'manage:OrganizationWarehouseCredentials',
        'manage:Organization',
        'manage:OrganizationColorPalette',
        'view:Roadmap',
        'impersonate:User',
        'manage:PersonalAccessToken',
    ],
};

const sortedUnique = (scopes: string[]) => [...new Set(scopes)].sort();

describe('given PROJECT_ROLE_TO_SCOPES_MAP is flattened from computed-cumulative to literal data', () => {
    describe.each(Object.values(ProjectMemberRole))(
        'when reading scopes for role %s',
        (role) => {
            it('then the exact same set of scopes as before flattening is produced', () => {
                expect(sortedUnique(PROJECT_ROLE_TO_SCOPES_MAP[role])).toEqual(
                    sortedUnique(GOLDEN_MASTER[role]),
                );
            });
        },
    );

    describe('when inspecting the module source', () => {
        const source = readFileSync(
            join(__dirname, 'roleToScopeMapping.ts'),
            'utf-8',
        );

        it.each([
            [
                'ROLE_HIERARCHY.indexOf',
                'per-role positional lookup into a hierarchy',
            ],
            ['new Set<string>()', 'runtime dedup-via-Set union'],
            [
                'Array.from(inheritedScopes',
                'materializing a runtime-computed Set',
            ],
        ])(
            'then it no longer contains the runtime-composition pattern %j (%s)',
            (pattern) => {
                expect(source).not.toContain(pattern);
            },
        );
    });
});
